import os

VT_API_KEY = os.getenv("VT_API_KEY", "")

LANG_EN = {
    'title': "=== Network Audit ===",
    'commands_title': "Available commands:",
    'list_cmd': "  list                    - List all connections",
    'list_pid': "  list <pid>              - List connections for a specific PID",
    'list_external': "  list external           - List connections to external IPs",
    'list_private': "  list private            - List connections to private IPs",
    'process_cmd': "  process <pid>           - Show detailed process information",
    'ipinfo_cmd': "  ipinfo <ip>             - Geolocate IP and optionally query VirusTotal",
    'summary_cmd': "  summary                 - Show general statistics",
    'export_cmd': "  export <file>           - Save network report to file",
    'npm_cmd': "  npm [path]              - Run NPM audit (default: current dir)",
    'npm_root_cmd': "  npm root                - Show npm installation locations",
    'npm_global_cmd': "  npm global              - List globally installed packages",
    'graph_cmd': "  graph                   - Show network topology",
    'kill_cmd': "  kill <pid>              - Kill a process by its PID",
    'help_cmd': "  help                    - Show this help",
    'exit_cmd': "  exit                    - Exit",
    
    # System Messages
    'invalid_cmd': "Unknown command. Type 'help'.",
    'usage_proc': "Usage: process <pid>",
    'pid_invalid': "Invalid PID",
    'proc_not_found': "Process not found or insufficient privileges.",
    'process_info': "\nProcess PID {pid}:",
    'usage_ipinfo': "Usage: ipinfo <ip>",
    'geoloc': "Geolocation: {}",
    'virustotal': "VirusTotal: {}",
    'summary': "\n=== SUMMARY ===",
    'total_conn': "Total connections: {}",
    'unique_pids': "Unique PIDs with connections: {}",
    'external_ips': "Unique external IPs: {}",
    'private_ips': "Unique private IPs: {}",
    'unusual_ports': "Unusual local ports: {}",
    'ports_list': "  Ports: {}",
    'usage_export': "Usage: export <file>",
    'export_ok': "Network report saved to {}",
    'export_err': "Error writing file: {}",
    'exit': "Exiting...",
    'pid': "PID",
    'proto': "Proto",
    'local': "Local",
    'remote': "Remote",
    'state': "State",
    'local_port': "Local Port",
    'total_shown': "Total: {}",
    'lang_prompt': "Select language / Seleccione idioma: (en/es): ",
    'lang_choice_invalid': "Invalid choice, defaulting to English.",
    'connections_obtained': "Retrieving network connections...",
    'no_connections': "No connections found or an error occurred.",
    'press_enter': "Press Enter to exit...",

    # NPM Audit Strings
    'npm_title': "Cerberus NPM Auditor",
    'npm_start': "Running NPM audit on {}...",
    'npm_project_title': "PROJECT DATA",
    'npm_config_title': "NPM CONFIGURATION",
    'npm_security_title': "SECURITY",
    'npm_size': "node_modules size",
    'npm_vulns': "Vulnerabilities",
    'npm_scripts': "Suspicious Scripts",
    'npm_malicious': "Malicious Packages",
    'npm_cache': "Cache Path",
    'npm_prefix': "Global Prefix",
    'npm_alert_script': "[bold yellow]⚠ ALERT:[/bold yellow] Script '[bold cyan]{}[/bold cyan]' contains: [dim]{}[/dim]",
    'npm_critical_malicious': "[bold red]❌ CRITICAL:[/bold red] Blacklisted package detected: [bold white]{}[/bold white]",
    'npm_locate_title': "NPM Installations Detected",
    'npm_path_col': "Binary Path",
    'npm_ver_col': "Version",
    'npm_global_list_title': "Globally installed packages:",
    'npm_not_installed': "npm is not installed or not available in PATH."
}

LANG_ES = {
    'title': "=== Auditoría de Red ===",
    'commands_title': "Comandos disponibles:",
    'list_cmd': "  list                    - Listar todas las conexiones",
    'list_pid': "  list <pid>              - Listar conexiones de un PID específico",
    'list_external': "  list externas           - Listar conexiones a IPs externas",
    'list_private': "  list privadas           - Listar conexiones a IPs privadas",
    'process_cmd': "  proceso <pid>           - Mostrar detalles del proceso",
    'ipinfo_cmd': "  ipinfo <ip>             - Geolocalizar IP y opcionalmente consultar VT",
    'summary_cmd': "  resumen                 - Mostrar estadísticas generales",
    'export_cmd': "  export <archivo>        - Guardar reporte de red en archivo",
    'npm_cmd': "  npm [ruta]              - Ejecutar auditoría NPM (por defecto actual)",
    'npm_root_cmd': "  npm raiz                - Mostrar rutas de instalación de NPM",
    'npm_global_cmd': "  npm globales            - Listar paquetes globales instalados",
    'graph_cmd': "  grafo                   - Mostrar topología de red",
    'kill_cmd': "  kill <pid>              - Terminar un proceso por su PID",
    'help_cmd': "  ayuda                   - Mostrar esta ayuda",
    'exit_cmd': "  salir                   - Salir",
    
    # Mensajes de Sistema
    'invalid_cmd': "Comando no reconocido. Escriba 'ayuda'.",
    'usage_proc': "Uso: proceso <pid>",
    'pid_invalid': "PID inválido",
    'proc_not_found': "Proceso no encontrado o sin permisos.",
    'process_info': "\nProceso PID {pid}:",
    'usage_ipinfo': "Uso: ipinfo <ip>",
    'geoloc': "Geolocalización: {}",
    'virustotal': "VirusTotal: {}",
    'summary': "\n=== RESUMEN ===",
    'total_conn': "Conexiones totales: {}",
    'unique_pids': "PIDs con conexiones: {}",
    'external_ips': "IPs externas únicas: {}",
    'private_ips': "IPs privadas únicas: {}",
    'unusual_ports': "Puertos locales inusuales: {}",
    'ports_list': "  Puertos: {}",
    'usage_export': "Uso: export <archivo>",
    'export_ok': "Reporte de red guardado en {}",
    'export_err': "Error al escribir archivo: {}",
    'exit': "Saliendo...",
    'pid': "PID",
    'proto': "Proto",
    'local': "Local",
    'remote': "Remoto",
    'state': "Estado",
    'local_port': "Puerto Local",
    'total_shown': "Total: {}",
    'lang_prompt': "Select language / Seleccione idioma: (en/es): ",
    'lang_choice_invalid': "Opción inválida, usando inglés por defecto.",
    'connections_obtained': "Obteniendo conexiones de red...",
    'no_connections': "No se encontraron conexiones o hubo un error.",
    'press_enter': "Presiona Enter para salir...",

    # NPM Auditoría
    'npm_title': "Cerberus Auditor de NPM",
    'npm_start': "Ejecutando auditoría NPM en {}...",
    'npm_project_title': "DATOS DEL PROYECTO",
    'npm_config_title': "CONFIGURACIÓN NPM",
    'npm_security_title': "SEGURIDAD",
    'npm_size': "Tamaño node_modules",
    'npm_vulns': "Vulnerabilidades",
    'npm_scripts': "Scripts Sospechosos",
    'npm_malicious': "Paquetes Maliciosos",
    'npm_cache': "Ruta de Caché",
    'npm_prefix': "Prefijo Global",
    'npm_alert_script': "[bold yellow]⚠ ALERTA:[/bold yellow] Script '[bold cyan]{}[/bold cyan]' contiene: [dim]{}[/dim]",
    'npm_critical_malicious': "[bold red]❌ CRÍTICO:[/bold red] Paquete en lista negra detectado: [bold white]{}[/bold white]",
    'npm_locate_title': "Instalaciones de NPM Detectadas",
    'npm_path_col': "Ruta del Binario",
    'npm_ver_col': "Versión",
    'npm_global_list_title': "Paquetes globales instalados:",
    'npm_not_installed': "npm no está instalado o no está disponible en el PATH."
}